### ISSUE TITLE
Villagers Opening Trade Menu when trying to pick them up

### ISSUE THREAD

**Issue by AnimeNerdDJBROS** [kwpugh/mob_catcher_catcher_fabric-1.17#1]
I did test in a single player world with only the mob catcher mod and this issue was solved, but it'd still be better to get some insight on both sides as to what's causing the issue. 

And an additional test on my showed despite what the mod author told me to do, I tested it and know that its not a mod confliction because I started up another world in singleplayer and it works fine. 

The issue here is that for some reason it doesn't work on villagers in multiplayer. Dunno why though.

**Comment by kwpugh** [comment]
ok, key tidbit here is multiplayer.   Let me check that out.

**Comment by kwpugh** [comment]
[MobCatcher-Fabric-1.17.1-1.0.4.jar.zip](https://github.com/kwpugh/mob_catcher_catcher_fabric-1.17/files/6794385/MobCatcher-Fabric-1.17.1-1.0.4.jar.zip)

Before I publish, can you please verify this version on your server.   It works on my server.

**Comment by AnimeNerdDJBROS** [comment]
1.0.2 The Latest one for 1.17 because 1.17.1 doesn't really have many mods rn and fabric causes things to conflict even if the version is only just slightly off, its weird.

**Comment by AnimeNerdDJBROS** [comment]
Oh, I misread. I'll test it on the server I'm hosting on.

**Comment by kwpugh** [comment]
the 1.17.1 version should work fine on 1.17

**Comment by AnimeNerdDJBROS** [comment]
For some reason , for me with only the latest version of Fabric API , Fabric and that MobCatcher version you sent prior. The server crashes on launch. 
[latest.log](https://github.com/kwpugh/mob_catcher_catcher_fabric-1.17/files/6794463/latest.log)

**Comment by AnimeNerdDJBROS** [comment]
Oh, I didn't know it attatches like that, heres the dropbox link so you can just view without needing to download. 
https://www.dropbox.com/s/1j38g6h148vub27/test.log?dl=0
I named it test.log there cuz I already have a latest.log in my dropbox for a separate issue.

**Comment by kwpugh** [comment]
Like most of my mods, MobCatcher requires Cloth Config for the config files

**Comment by AnimeNerdDJBROS** [comment]
Ah okay, sorry about that. I'll double check that now.

**Comment by AnimeNerdDJBROS** [comment]
> [MobCatcher-Fabric-1.17.1-1.0.4.jar.zip](https://github.com/kwpugh/mob_catcher_catcher_fabric-1.17/files/6794385/MobCatcher-Fabric-1.17.1-1.0.4.jar.zip)
> 
> Before I publish, can you please verify this version on your server. It works on my server.

Sorry for the time taken on this. But the issue is fixed in the version sent prior. Just tested it after dealing with a few different problems.
