### ISSUE TITLE
Doen't work on Villagers on servers

### ISSUE THREAD

**Issue by ravensniper72** [kwpugh/mob_catcher_catcher_fabric-1.17#2]
I have tested in singleplayer and multiplayer with my modpack and it does not seem to work on villagers on servers but works fine in singleplayer.

**Comment by kwpugh** [comment]
Are you using version. MobCatcher-Fabric-1.17.1-1.0.4.jar
 
I specifically fixed and tested that issue on my own server.

**Comment by ravensniper72** [comment]
Is it possible to fix that for 1.17? I have a server that me and buddies play on and it kind of sucks not having that work.

**Comment by kwpugh** [comment]
use  MobCatcher-Fabric-1.17.1-1.0.4.jar, it fits the problem.   it runs on 1.17 fine.

**Comment by kwpugh** [comment]
in general, you should use the 1.17.1 version of mods on 1.17.   Most are no longer updating the 1.17 version with bug fixes.
